services:
  db:
    image: pgvector/pgvector:pg17
    volumes:
      - pgdata:/var/lib/postgresql/
    environment:
      POSTGRES_USER: db_user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: db_password
    ports:
      - "127.0.0.1:${PORT_DB:-5432}:5432"

  app:
    build: .
    image: ${COMPOSE_PROJECT_NAME}
    entrypoint: ./entrypoint.sh
    ports:
      - "127.0.0.1:${API_PORT:-8000}:8000"
    env_file:
      - .env
    restart: always
    environment:
      DATABASE_URL: postgresql+psycopg://db_user:db_password@db:5432/db
    depends_on:
      - db

volumes:
  pgdata:
